### ISSUE TITLE
short cut key

### ISSUE THREAD

**Issue by vbpatel73** [CharltonC/chrome-css-selector-highlight#1]
hi, do you have short cut key to copy selector automatically?

**Comment by CharltonC** [comment]
@vbpatel73 
At the moment only two shortcut keys as per documentation. Can you let me know a bit more on how you would use this feature so that I take a closer look?
I would be very cautious regarding tapping into or interfering with the existing page where the extension is run. The existing page may already have its own short cut keys and so does Chrome. So the idea is the less possibility of interference with the page, the better. 
Cheers,

**Comment by CharltonC** [comment]
Closing the issue due to inactivity

**Comment by CharltonC** [comment]
Closing the issue due to inactivity

**Comment by CharltonC** [comment]
Closing it for inactivity

**Comment by nathgit** [comment]
Is there any chance of a shortcut being added to copy selector or to lock selector? It's difficult to copy a selector when moving the mouse highlights different selector.
