### ISSUE TITLE
while the web pages contains frame,this tool can not swtich to the frame but always stay in the top

### ISSUE THREAD

**Issue by Summer-Shen98** [CharltonC/chrome-css-selector-highlight#4]
while the web pages contains frame,this tool can not swtich to the frame but always stay in the top
I think this may can be resolved?

**Comment by CharltonC** [comment]
Hey @summeer1998 ,
Thanks for posting the issue. You will need something like Xpath to deal with that scenario because CSS (include CSS Selector) is only scoped to the same document (where iframe is another document) hence only works for that page. See url reference https://stackoverflow.com/questions/21842373/css-selector-for-when-a-html-document-is-inside-an-iframe. Alternatively you can open the the frame Url in a standalone window directly and run the extension in that context. Hope this helps! 
Cheers,
